services:
  # NextJS Application
  nextjs:
    image: inderharrysingh/amul-nextjs:latest
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=${NODE_ENV}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - REDIS_URL=${REDIS_URL}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
    depends_on:
      - postgres
      - redis
    env_file:
      - .env.prod

  # Cron Job
  cron:
    image: inderharrysingh/amul-cron:latest
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=${NODE_ENV}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - postgres
      - redis
    env_file:
      - .env.prod

  # Worker
  worker:
    image: inderharrysingh/amul-worker:latest
    environment:
      - REDIS_URL=${REDIS_URL}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - RESEND_FROM_EMAIL=${RESEND_FROM_EMAIL}
    depends_on:
      - redis
    env_file:
      - .env.prod

  # Redis
  redis:
    image: redis:8-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    env_file:
      - .env.prod

  # PostgreSQL
  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.prod

  migrate:
    image: inderharrysingh/amul-migration:latest
    command: pnpm db:migrate
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
    env_file:
      - .env.prod
    profiles:
      - tools

  seed:
    image: inderharrysingh/amul-migration:latest
    command: pnpm db:seed
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
    env_file:
      - .env.prod
    profiles:
      - tools

volumes:
  redis_data:
  postgres_data:
